Repository ForesightMiningSoftwareCorporation/bevy_fsl_box_frame, pull requests merged in 2025-01, with the labels that each got.

#12 Fix panic when dragging faces
  src/drag_face.rs
Labels: size/XS

#13 add OWNERS
  OWNERS
Labels: approved, size/XS

#14 release 0.4.1
  Cargo.toml
Labels: approved, lgtm, size/XS
